layout: {qmk_keyboard: lily58_rotated}
layers:
  default:
  - {t: ESC, s: '`'}
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - \
  - LCTRL
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - '['
  - ']'
  - N
  - M
  - ','
  - .
  - /
  - '&rshift_caps'
  - LALT
  - LGUI
  - lower
  - SPACE
  - {t: RET, h: Ctl+Alt+ LGUI}
  - raise
  - RGUI
  - RALT
  lower:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ESC, s: '`'}
  - '['
  - '{'
  - (
  - '~'
  - ^
  - )
  - '}'
  - ']'
  - '`'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - '='
  - +
  - '*'
  - /
  - '#'
  - {t: RGUI, h: sticky}
  - {t: RALT, h: sticky}
  - {t: RCTRL, h: sticky}
  - {t: RSHFT, h: sticky}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - _
  - '&'
  - '|'
  - '?'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  raise:
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: LSHFT, h: sticky}
  - {t: LCTRL, h: sticky}
  - {t: LALT, h: sticky}
  - {t: LGUI, h: sticky}
  - ''
  - LARW
  - DARW
  - UARW
  - RARW
  - BRI UP
  - VOL UP
  - ''
  - ''
  - ''
  - PREV
  - NEXT
  - PP
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - BRI DN
  - VOL DN
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  fn:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - F1
  - F2
  - F3
  - F4
  - ''
  - ''
  - F5
  - F6
  - F7
  - F8
  - ''
  - ''
  - {t: LSHFT, h: sticky}
  - {t: LCTRL, h: sticky}
  - {t: LALT, h: sticky}
  - {t: LGUI, h: sticky}
  - ''
  - ''
  - {t: RGUI, h: sticky}
  - {t: RALT, h: sticky}
  - {t: RCTRL, h: sticky}
  - {t: RSHFT, h: sticky}
  - ''
  - ''
  - F9
  - F10
  - F11
  - F12
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
